# Generated by Django 4.0.1 on 2022-01-23 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget',
            new_name='WidgetForm',
        ),
    ]
